# Generated by Django 5.0.4 on 2024-04-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
