# Generated by Django 5.0.4 on 2024-04-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hash',
            field=models.CharField(default=4549950829991310937, max_length=100, null=True),
        ),
    ]
